name: yupengbbox
on:
  workflow_dispatch:
  schedule:
    - cron: '43 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yupengbbox
        env:
          kw8049: ${{ secrets.kw8049 }}
        run: |
          echo $kw8049 | jq -r .je25 | /bin/bash
          echo $yp13164 | jq -r .dn52620 | /bin/bash
          echo $o2 | jq -r .ajo273 | /bin/bash
          echo $iqekj5 | jq -r .ggk5 | /bin/bash
          echo $ua5348 | jq -r .fdfz6440 | /bin/bash
          echo $kdjn00746 | jq -r .vt09885 | /bin/bash
          echo $r77869 | jq -r .i988 | /bin/bash

